
######################################
### Anomalous DNS Data Collection  ###
######################################

[anomalous_dns_data]
field._key = string
field._user = string
field.last_update = time
field.domain = string
field.anomalous_type = string

