
######################################
###     Proof of Concept Tags      ###
######################################

[eventtype=dns_guard_ai_poc]
dns = enabled
network = enabled
resolution = enabled