
######################################
###     Anomalous DNS KV Store     ###
######################################

[anomalous_dns_lookup]
external_type = kvstore
collection = anomalous_dns_data
fields_list = _key, _user, last_update, domain, anomalous_type
# _key = domain#anomalous_type

######################################
###     Whitelist Domain CSV       ###
######################################

[whitelist_domain_lookup]
filename = whitelist_domain.csv
external_type = csv
fields_list = domain